# Generated by Django 5.2 on 2025-06-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_slug_product_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
